#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Print the Homebrew formula for a published release, with the tarball checksums filled in:
#
#   scripts/homebrew-formula.sh 0.3.0 > ../homebrew-mtr-rs/Formula/mtr-rs.rb
#
# The tap lives at https://github.com/seitzbg/homebrew-mtr-rs. The formula installs the
# prebuilt release tarballs (macOS and Linux, both architectures); Homebrew does not install
# setuid binaries, so the raw-socket privilege for mtr-rs-packet is a caveat, as it is for the
# core `mtr` formula.
set -euo pipefail
version=${1:?usage: homebrew-formula.sh VERSION}
base="https://github.com/seitzbg/mtr-rs/releases/download/v$version"

sha() { curl -fsSL "$base/mtr-rs-$version-$1.tar.gz" | sha256sum | cut -d' ' -f1; }
arm_mac=$(sha aarch64-macos); x86_mac=$(sha x86_64-macos)
arm_linux=$(sha aarch64-linux); x86_linux=$(sha x86_64-linux)

cat <<RUBY
# SPDX-License-Identifier: GPL-2.0-only
# Generated by scripts/homebrew-formula.sh in seitzbg/mtr-rs; edit there, not here.
class MtrRs < Formula
  desc "Rust port of mtr (My TraceRoute) with a terminal UI and classic reports"
  homepage "https://github.com/seitzbg/mtr-rs"
  version "$version"
  license "GPL-2.0-only"

  on_macos do
    on_arm do
      url "$base/mtr-rs-$version-aarch64-macos.tar.gz"
      sha256 "$arm_mac"
    end
    on_intel do
      url "$base/mtr-rs-$version-x86_64-macos.tar.gz"
      sha256 "$x86_mac"
    end
  end

  on_linux do
    on_arm do
      url "$base/mtr-rs-$version-aarch64-linux.tar.gz"
      sha256 "$arm_linux"
    end
    on_intel do
      url "$base/mtr-rs-$version-x86_64-linux.tar.gz"
      sha256 "$x86_linux"
    end
  end

  def install
    bin.install "bin/mtr-rs", "bin/mtr-rs-packet"
    man8.install "man/mtr-rs.8", "man/mtr-rs-packet.8"
    bash_completion.install "completions/mtr-rs.bash" => "mtr-rs"
    zsh_completion.install "completions/_mtr-rs"
    fish_completion.install "completions/mtr-rs.fish"
  end

  def caveats
    on_macos do
      <<~EOS
        mtr-rs-packet opens raw sockets, which need root. Either run \`sudo mtr-rs\`, or let
        the helper start as root on its own (it drops back to you once its sockets are open);
        Homebrew cannot do that step, so repeat it after every install or upgrade:
          sudo chown root:wheel #{opt_bin}/mtr-rs-packet && sudo chmod u+s #{opt_bin}/mtr-rs-packet
      EOS
    end
    on_linux do
      <<~EOS
        mtr-rs-packet needs cap_net_raw for raw sockets; grant it once per install or upgrade:
          sudo setcap cap_net_raw+ep #{opt_bin}/mtr-rs-packet
        Without it the helper falls back to unprivileged ICMP sockets (see the README).
      EOS
    end
  end

  test do
    assert_match "mtr-rs #{version}", shell_output("#{bin}/mtr-rs --version")
    assert_match "Usage: mtr-rs", shell_output("#{bin}/mtr-rs --help")
  end
end
RUBY
